version: '3.8'

services:
  api_test:
    build:
      context: .
      dockerfile: docker/Dockerfile.test
    container_name: political-feed-api-test
    volumes:
      - ./test-reports:/app/test-reports
    environment:
      - TESTING=True
      - DATABASE_URL=sqlite:///./test.db
      - SECRET_KEY=testsecretkey
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30