version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: political-feed-api
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
      - ./scripts:/app/scripts
      - ./scripts/test_data:/app/scripts/test_data
      - ./tests:/app/tests
      - ./.flake8:/app/.flake8
      - ./.isort.cfg:/app/.isort.cfg
      - ./pyproject.toml:/app/pyproject.toml
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://political_user:political_password@db:3306/political_feed_db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY:-supersecretkey}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ENVIRONMENT=development
      - CORS_ORIGINS=["http://localhost:3000","http://127.0.0.1:3000"]
    depends_on:
      - db
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - political-feed-network

  db:
    image: mysql:8.0
    container_name: political-feed-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=political_feed_db
      - MYSQL_USER=political_user
      - MYSQL_PASSWORD=political_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - political-feed-network

  redis:
    image: redis:6-alpine
    container_name: political-feed-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - political-feed-network

  celery_worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: political-feed-celery
    volumes:
      - ./app:/app/app
    environment:
      - DATABASE_URL=mysql+pymysql://political_user:political_password@db:3306/political_feed_db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY:-supersecretkey}
      - ENVIRONMENT=development
    depends_on:
      - db
      - redis
    command: celery -A app.tasks.worker worker --loglevel=info
    networks:
      - political-feed-network

  minio:
    image: minio/minio
    container_name: political-feed-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - political-feed-network

networks:
  political-feed-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
  minio_data: